import React, { useMemo, useState } from 'react';
import { FlaskConical, Info, TrendingDown, TrendingUp } from 'lucide-react';
import type { FinancialHomeResponse, PortfolioSummary } from '../../types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/Card';

interface DecisionLabTabProps { home: FinancialHomeResponse | null; portfolio: PortfolioSummary | null; }
type ScenarioType = 'one-time-purchase' | 'monthly-investment' | 'emergency-catch-up' | 'budget-change' | 'debt-change' | 'income-change' | 'goal-change' | 'asset-decline';
const descriptions: Record<ScenarioType, string> = { 'one-time-purchase': 'Model a one-time cash purchase.', 'monthly-investment': 'Model a recurring investment contribution.', 'emergency-catch-up': 'Reserve more cash for resilience.', 'budget-change': 'Raise or lower planned flexible spending.', 'debt-change': 'Increase debt payoff for this period.', 'income-change': 'Model an income increase or missed income.', 'goal-change': 'Increase a goal contribution.', 'asset-decline': 'Model a percentage decline in the portfolio.' };
const format = (value: number, currency: string) => `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })} ${currency}`;

export const DecisionLabTab: React.FC<DecisionLabTabProps> = ({ home, portfolio }) => {
  const [type, setType] = useState<ScenarioType>('one-time-purchase'); const [amount, setAmount] = useState('500');
  const result = useMemo(() => {
    if (!home) return null; const value = Number(amount) || 0; const snapshot = home.snapshot; const sign = type === 'income-change' ? 1 : -1;
    const cashImpact = type === 'asset-decline' ? 0 : sign * value; const investmentImpact = type === 'monthly-investment' ? value : type === 'asset-decline' ? -(portfolio?.marketValue || 0) * value / 100 : 0;
    const safe = Math.max(0, snapshot.safeToSpend + cashImpact); const end = snapshot.forecast.expected + cashImpact;
    const runway = snapshot.safeToSpend > 0 ? (snapshot.buffer.coverageMonths * safe / Math.max(1, snapshot.safeToSpend)) : 0;
    const portfolioValue = Math.max(0, (portfolio?.marketValue || snapshot.investmentMarketValue) + investmentImpact);
    return { safe, end, runway, portfolioValue, buffer: type === 'emergency-catch-up' ? snapshot.buffer.current + value : snapshot.buffer.current, goalFeasibility: type === 'goal-change' ? 'Contribution increases; review your plan’s unallocated margin.' : 'Unchanged unless you convert this scenario into a plan.', debt: type === 'debt-change' ? 'Payoff timeline improves; safe spending capacity falls by the same amount.' : 'No direct debt-timeline change.' };
  }, [amount, home, portfolio, type]);
  if (!home || !result) return <div className="rounded-xl border border-dashed p-6 text-sm text-gray-500">Decision Lab will be available with your Financial Home snapshot.</div>;
  const currency = home.profile.baseCurrency;
  return <div className="mx-auto max-w-5xl space-y-5 pb-12"><div><p className="text-sm font-medium text-indigo-600">Plan · Decision Lab</p><h2 className="text-2xl font-bold">Test a decision without changing your money.</h2><p className="mt-1 text-sm text-gray-500">This simulation never writes transactions, plans, budgets, or investment events. Convert a result to a reviewed plan only when you choose.</p></div><Card className="border-indigo-200 dark:border-indigo-900"><CardHeader><CardTitle className="flex items-center gap-2"><FlaskConical className="h-5 w-5 text-indigo-600" />Scenario</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">What changes?<select value={type} onChange={(event) => setType(event.target.value as ScenarioType)} className="mt-1 w-full rounded-md border bg-transparent p-2">{(Object.keys(descriptions) as ScenarioType[]).map((option) => <option key={option} value={option}>{option.replaceAll('-', ' ')}</option>)}</select><span className="mt-1 block text-xs text-gray-500">{descriptions[type]}</span></label><label className="text-sm font-medium">{type === 'asset-decline' ? 'Decline percentage' : `Amount (${currency})`}<input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} className="mt-1 w-full rounded-md border bg-transparent p-2" /></label></CardContent></Card><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Outcome label="Safe to spend" before={home.snapshot.safeToSpend} after={result.safe} currency={currency} /><Outcome label="Forecast end balance" before={home.snapshot.forecast.expected} after={result.end} currency={currency} /><Outcome label="Portfolio value" before={portfolio?.marketValue || home.snapshot.investmentMarketValue} after={result.portfolioValue} currency={currency} /><Outcome label="Emergency buffer" before={home.snapshot.buffer.current} after={result.buffer} currency={currency} /><Card><CardHeader><CardTitle className="text-sm text-gray-500">Runway proxy</CardTitle></CardHeader><CardContent><p className="text-xl font-bold">{result.runway.toFixed(1)} months</p><p className="mt-1 text-xs text-gray-500">Planning estimate based on the existing buffer/spend relationship.</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm text-gray-500">Goal / debt effect</CardTitle></CardHeader><CardContent><p className="text-sm">{result.goalFeasibility}</p><p className="mt-2 text-xs text-gray-500">{result.debt}</p></CardContent></Card></div><div className="flex gap-2 rounded-xl border border-sky-200 bg-sky-50 p-4 text-sm text-sky-900 dark:border-sky-900 dark:bg-sky-950/30 dark:text-sky-100"><Info className="h-4 w-4 shrink-0" />This result is a forecast based on current recorded data. It is not a live change and does not guarantee a financial outcome.</div></div>;
};
const Outcome: React.FC<{ label: string; before: number; after: number; currency: string }> = ({ label, before, after, currency }) => { const increase = after >= before; return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-sm text-gray-500">{increase ? <TrendingUp className="h-4 w-4 text-emerald-600" /> : <TrendingDown className="h-4 w-4 text-red-600" />}{label}</CardTitle></CardHeader><CardContent><p className="text-xl font-bold">{format(after, currency)}</p><p className={`mt-1 text-xs ${increase ? 'text-emerald-600' : 'text-red-600'}`}>{increase ? '+' : ''}{format(after - before, currency)} vs. current</p></CardContent></Card>; };
