import React from 'react';
import { Flag, Landmark, PiggyBank, ShieldCheck, Target, TrendingUp } from 'lucide-react';
import type { Debt, FinancialHomeResponse, Goal, PortfolioSummary } from '../../types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/Card';

interface FinancialRoadmapTabProps { home: FinancialHomeResponse | null; goals: Goal[]; debts: Debt[]; portfolio: PortfolioSummary | null; }
const value = (amount: string | number) => Number(amount) || 0;
const cash = (amount: number, currency: string) => `${amount.toLocaleString(undefined, { maximumFractionDigits: 2 })} ${currency}`;

export const FinancialRoadmapTab: React.FC<FinancialRoadmapTabProps> = ({ home, goals, debts, portfolio }) => {
  if (!home) return <div className="rounded-xl border border-dashed p-6 text-sm text-gray-500">Your roadmap will be ready once Financial Home data is available.</div>;
  const { snapshot, profile } = home;
  const currency = profile?.baseCurrency || 'MAD';
  const payables = debts.filter((debt) => debt.type === 'Payable' && debt.status === 'Pending');
  return <div className="mx-auto max-w-6xl space-y-5 pb-12"><div><p className="text-sm font-medium text-indigo-600">Wealth · Financial Roadmap</p><h2 className="text-2xl font-bold">See trade-offs across cash, goals, debt, and investing.</h2><p className="mt-1 text-sm text-gray-500">Cash facts are shown separately from forecasts, which depend on recorded commitments and your current plan.</p></div>
    <div className="grid gap-4 lg:grid-cols-2"><Track icon={<PiggyBank className="h-5 w-5 text-emerald-600" />} title="Emergency fund" subtitle={`${(snapshot?.buffer?.coverageMonths ?? 0).toFixed(1)} months of essential coverage`} current={snapshot?.buffer?.current ?? 0} target={snapshot?.buffer?.target ?? 0} currency={currency} footer={`Protected cash: ${cash(snapshot?.protectedEmergencyCash ?? 0, currency)}`} /><Card><CardHeader><CardTitle className="flex items-center gap-2"><Landmark className="h-5 w-5 text-red-600" />Debt roadmap</CardTitle><CardDescription>Outstanding payables and their recorded due dates.</CardDescription></CardHeader><CardContent>{payables.length ? <div className="space-y-2">{payables.map((debt) => <div key={debt.id} className="flex justify-between rounded-lg border p-3"><span>{debt.contactName}<span className="block text-xs text-gray-500">{debt.dueDate ? `Due ${new Date(debt.dueDate).toLocaleDateString()}` : 'No due date recorded'}</span></span><strong>{cash(value(debt.remainingBalance), currency)}</strong></div>)}</div> : <p className="text-sm text-gray-500">No pending payables.</p>}</CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5 text-indigo-600" />Goals</CardTitle><CardDescription>Deadline feasibility is based on required period contributions, not wishful forecasts.</CardDescription></CardHeader><CardContent className="space-y-3">{goals.length ? goals.map((goal) => { const current = value(goal.currentAmount); const target = value(goal.targetAmount); const pct = target ? Math.min(100, current * 100 / target) : 0; const deadline = goal.deadline ? new Date(goal.deadline) : null; const months = deadline ? Math.max(1, Math.ceil((deadline.getTime() - Date.now()) / (30.4375 * 86_400_000))) : null; const needed = months ? Math.max(0, target - current) / months : 0; return <div key={goal.id} className="rounded-lg border p-3"><div className="flex justify-between gap-3"><strong>{goal.name}</strong><span>{cash(current, currency)} / {cash(target, currency)}</span></div><div className="mt-2 h-2 rounded-full bg-gray-100 dark:bg-gray-800"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${pct}%` }} /></div><p className="mt-2 text-xs text-gray-500">{deadline ? `${cash(needed, currency)} per month needed by ${deadline.toLocaleDateString()}` : 'No deadline recorded; choose one to assess feasibility.'}</p></div>; }) : <p className="text-sm text-gray-500">Create a goal to include it in the roadmap.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-amber-600" />Investing</CardTitle><CardDescription>Wealth remains separate from emergency cash unless you explicitly mark a cash-like asset eligible.</CardDescription></CardHeader><CardContent><p className="text-2xl font-bold">{cash(portfolio?.marketValue || 0, currency)}</p><p className="mt-1 text-sm text-gray-500">{portfolio?.holdings?.length || 0} holdings · {cash(snapshot?.investmentCapacity ?? 0, currency)} current planning ceiling.</p><div className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900 dark:bg-amber-950/30 dark:text-amber-100"><ShieldCheck className="mr-1 inline h-4 w-4" />Capacity is an upper bound after bills, debts, goals, flexible spending, and safety margin—not a recommendation to invest it all.</div></CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Flag className="h-5 w-5 text-indigo-600" />Financial position</CardTitle><CardDescription>Facts as of {snapshot?.asOf ? new Date(snapshot.asOf).toLocaleString() : 'now'}; forecasts below use your recorded spending pace.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-4"><Fact label="Liquid cash" value={cash(snapshot?.liquidCash ?? 0, currency)} /><Fact label="Reserved / protected" value={cash((snapshot?.protectedEmergencyCash ?? 0) + (snapshot?.reservedForCommitments ?? 0) + (snapshot?.reservedForGoals ?? 0), currency)} /><Fact label="Investment value" value={cash(snapshot?.investmentMarketValue ?? 0, currency)} /><Fact label="Net worth" value={cash(snapshot?.netWorth ?? 0, currency)} /></CardContent></Card>
  </div>;
};
const Track: React.FC<{ icon: React.ReactNode; title: string; subtitle: string; current: number; target: number; currency: string; footer: string }> = ({ icon, title, subtitle, current, target, currency, footer }) => <Card><CardHeader><CardTitle className="flex items-center gap-2">{icon}{title}</CardTitle><CardDescription>{subtitle}</CardDescription></CardHeader><CardContent><div className="flex justify-between"><strong>{cash(current, currency)}</strong><span className="text-gray-500">Target {cash(target, currency)}</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-gray-100 dark:bg-gray-800"><div className="h-full bg-emerald-500" style={{ width: `${Math.min(100, target ? current * 100 / target : 0)}%` }} /></div><p className="mt-3 text-sm text-gray-500">{footer}</p></CardContent></Card>;
const Fact: React.FC<{ label: string; value: string }> = ({ label, value }) => <div className="rounded-lg bg-gray-50 p-3 dark:bg-gray-800"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>;
