import React, { useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, CircleDollarSign, Landmark, LineChart, Plus, RefreshCcw, ShieldAlert, TrendingDown, TrendingUp } from 'lucide-react';
import { Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import type { InvestmentAccount, InvestmentAccountType, InvestmentAsset, InvestmentEvent, PortfolioSummary, RiskLevel, Wallet } from '../../types';
import { Button } from '../ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/Card';

interface PortfolioTabProps {
  portfolio: PortfolioSummary | null;
  accounts: InvestmentAccount[];
  assets: InvestmentAsset[];
  events: InvestmentEvent[];
  wallets: Wallet[];
  saving: boolean;
  onCreateAccount: (input: Omit<InvestmentAccount, 'id' | 'userId' | 'createdAt' | 'updatedAt' | 'isArchived'>) => Promise<InvestmentAccount | undefined>;
  onCreateAsset: (input: Omit<InvestmentAsset, 'id' | 'userId' | 'createdAt' | 'updatedAt' | 'isActive'>) => Promise<InvestmentAsset | undefined>;
  onCreateEvent: (input: { investmentAccountId: string; assetId?: string | null; type: InvestmentEvent['type']; tradeDate?: string; units?: number; unitPrice?: number; quoteCurrency?: string; grossAmount: number; feeAmount?: number; feeCurrency?: string; exchangeRateToBase?: number; notes?: string }) => Promise<InvestmentEvent | undefined>;
  onFund: (id: string, payload: { sourceWalletId: string; amount: number; date?: string; note?: string }) => Promise<unknown>;
  onManualPrice: (input: { assetId: string; price: number; currency: string; capturedAt?: string }) => Promise<unknown>;
  onRefreshPrices: () => Promise<{ refreshed: number; stale: boolean; message: string } | undefined>;
  onSearchCrypto: (query: string) => Promise<Array<{ id: string; name: string; symbol: string; marketCapRank: number | null; image: string | null }>>;
}

const colors = ['#4f46e5', '#0ea5e9', '#10b981', '#f59e0b', '#ef4444', '#a855f7'];
const asNumber = (value: string | number | undefined | null) => Number(value || 0) || 0;
const money = (value: number, currency: string) => `${value.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 })} ${currency}`;

export const PortfolioTab: React.FC<PortfolioTabProps> = ({ portfolio, accounts, assets, events, wallets, saving, onCreateAccount, onCreateAsset, onCreateEvent, onFund, onManualPrice, onRefreshPrices, onSearchCrypto }) => {
  const [showAccount, setShowAccount] = useState(false); const [showAsset, setShowAsset] = useState(false); const [showTrade, setShowTrade] = useState(false); const [showFund, setShowFund] = useState(false); const [showPrice, setShowPrice] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [cryptoQuery, setCryptoQuery] = useState('');
  const [cryptoResults, setCryptoResults] = useState<Array<{ id: string; name: string; symbol: string; marketCapRank: number | null; image: string | null }>>([]);
  const [searchingCrypto, setSearchingCrypto] = useState(false);
  const [accountForm, setAccountForm] = useState({ name: '', institution: '', type: 'Exchange' as InvestmentAccountType, baseCurrency: portfolio?.baseCurrency || 'MAD', liquidity: 'Restricted' as InvestmentAccount['liquidity'], includeInNetWorth: true, includeInEmergencyReserve: false });
  const [assetForm, setAssetForm] = useState({ symbol: '', name: '', assetClass: 'Crypto' as InvestmentAsset['assetClass'], coinGeckoCoinId: '', quoteCurrency: portfolio?.baseCurrency || 'MAD', unitsPrecision: 8, riskLevel: 'High' as RiskLevel, marketDataProvider: null as string | null });
  const [tradeForm, setTradeForm] = useState({ investmentAccountId: '', assetId: '', type: 'Buy' as InvestmentEvent['type'], units: '', unitPrice: '', grossAmount: '', feeAmount: '0', tradeDate: new Date().toISOString().slice(0, 10), notes: '' });
  const [fundForm, setFundForm] = useState({ accountId: '', sourceWalletId: '', amount: '' }); const [priceForm, setPriceForm] = useState({ assetId: '', price: '', currency: portfolio?.baseCurrency || 'MAD' });
  const activeAccounts = accounts.filter((account) => !account.isArchived); const currency = portfolio?.baseCurrency || 'MAD';
  const holdingsByAsset = useMemo(() => new Map(portfolio?.holdings.map((holding) => [holding.asset.id, holding]) || []), [portfolio]);
  const handle = async (task: () => Promise<unknown>, success: string) => { try { await task(); setMessage(success); } catch (error) { setMessage(error instanceof Error ? error.message : 'The operation could not be completed.'); } };
  const submitAccount = (event: React.FormEvent) => { event.preventDefault(); handle(async () => { const created = await onCreateAccount(accountForm); if (created) { setShowAccount(false); setAccountForm({ ...accountForm, name: '', institution: '' }); } }, 'Investment account created.'); };
  const submitAsset = (event: React.FormEvent) => { event.preventDefault(); handle(async () => { const created = await onCreateAsset({ ...assetForm, coinGeckoCoinId: assetForm.coinGeckoCoinId || null, marketDataProvider: assetForm.coinGeckoCoinId ? 'CoinGecko' : null }); if (created) { setShowAsset(false); setAssetForm({ ...assetForm, symbol: '', name: '', coinGeckoCoinId: '' }); } }, 'Asset added to your manual portfolio registry.'); };
  const submitTrade = (event: React.FormEvent) => { event.preventDefault(); handle(async () => { const gross = asNumber(tradeForm.grossAmount) || asNumber(tradeForm.units) * asNumber(tradeForm.unitPrice); await onCreateEvent({ investmentAccountId: tradeForm.investmentAccountId, assetId: tradeForm.assetId || null, type: tradeForm.type, units: asNumber(tradeForm.units) || undefined, unitPrice: asNumber(tradeForm.unitPrice) || undefined, grossAmount: gross, feeAmount: asNumber(tradeForm.feeAmount), tradeDate: tradeForm.tradeDate, notes: tradeForm.notes, quoteCurrency: currency }); setShowTrade(false); }, 'Investment event recorded in the immutable portfolio ledger.'); };
  const submitFund = (event: React.FormEvent) => { event.preventDefault(); handle(async () => { await onFund(fundForm.accountId, { sourceWalletId: fundForm.sourceWalletId, amount: asNumber(fundForm.amount) }); setShowFund(false); }, 'Investment account funding recorded as a transfer, not an expense.'); };
  const submitPrice = (event: React.FormEvent) => { event.preventDefault(); handle(async () => { await onManualPrice({ assetId: priceForm.assetId, price: asNumber(priceForm.price), currency: priceForm.currency }); setShowPrice(false); }, 'Manual price saved. It changes portfolio valuation, never wallet cash.'); };
  const refresh = () => handle(async () => { const result = await onRefreshPrices(); if (result) setMessage(result.message); }, 'Price refresh complete.');
  const searchCrypto = async () => {
    if (!cryptoQuery.trim()) return;
    setSearchingCrypto(true);
    try { setCryptoResults(await onSearchCrypto(cryptoQuery)); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Crypto search is unavailable. You can still add a manual asset.'); }
    finally { setSearchingCrypto(false); }
  };
  const selectCrypto = (result: { id: string; name: string; symbol: string }) => {
    setAssetForm({ ...assetForm, symbol: result.symbol, name: result.name, coinGeckoCoinId: result.id, assetClass: 'Crypto', riskLevel: 'High', marketDataProvider: 'CoinGecko' });
    setCryptoResults([]);
  };

  return <div className="mx-auto max-w-7xl space-y-5 pb-12"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-indigo-600">Wealth · Portfolio</p><h2 className="text-2xl font-bold">Track investments without confusing them with spendable cash.</h2><p className="mt-1 text-sm text-gray-500">Planning guidance only—not a guarantee or regulated investment recommendation. Volatile assets can lose value.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={refresh} disabled={saving}><RefreshCcw className="mr-1 h-4 w-4" />Refresh crypto prices</Button><Button onClick={() => setShowAccount(true)}><Plus className="mr-1 h-4 w-4" />Account</Button></div></div>
    {message && <div role="status" className="rounded-xl border border-indigo-200 bg-indigo-50 p-3 text-sm text-indigo-900 dark:border-indigo-900 dark:bg-indigo-950/30 dark:text-indigo-100">{message}</div>}
    {portfolio?.priceFreshness === 'stale' && <div className="flex gap-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle className="h-4 w-4 shrink-0" />Provider prices are stale. The last successful valuation remains visible and wallet balances have not changed.</div>}
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><Metric title="Portfolio market value" value={money(portfolio?.marketValue || 0, currency)} icon={<LineChart className="h-5 w-5 text-indigo-600" />} /><Metric title="Net deposits" value={money(portfolio?.totalContributions || 0, currency)} icon={<Landmark className="h-5 w-5 text-sky-600" />} /><Metric title="Unrealized gain / loss" value={money(portfolio?.unrealizedGain || 0, currency)} icon={(portfolio?.unrealizedGain || 0) >= 0 ? <TrendingUp className="h-5 w-5 text-emerald-600" /> : <TrendingDown className="h-5 w-5 text-red-600" />} /><Metric title="Realized gain / loss" value={money(portfolio?.realizedGain || 0, currency)} icon={<BarChart3 className="h-5 w-5 text-violet-600" />} /><Metric title="Total return" value={`${(portfolio?.totalReturnPercent || 0).toFixed(2)}%`} icon={<CircleDollarSign className="h-5 w-5 text-amber-600" />} /></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-indigo-600" />Allocation by asset class</CardTitle></CardHeader><CardContent className="h-72">{portfolio?.allocationByAssetClass.length ? <ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={portfolio.allocationByAssetClass} dataKey="value" nameKey="name" outerRadius={85}>{portfolio.allocationByAssetClass.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip formatter={(value: number) => money(value, currency)} /><Legend /></PieChart></ResponsiveContainer> : <Empty text="Record an asset purchase and a manual or provider price to see allocation." />}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-amber-600" />Risk concentration</CardTitle></CardHeader><CardContent className="space-y-3">{portfolio?.riskConcentration.length ? portfolio.riskConcentration.map((risk) => <div key={risk.risk}><div className="flex justify-between text-sm"><span>{risk.risk}</span><span>{risk.percent.toFixed(1)}%</span></div><div className="mt-1 h-2 rounded-full bg-gray-100 dark:bg-gray-800"><div className="h-full rounded-full bg-amber-500" style={{ width: `${risk.percent}%` }} /></div></div>) : <Empty text="Risk concentration appears once assets have a valuation." />}</CardContent></Card></div>
    <Card><CardHeader><div className="flex flex-wrap justify-between gap-3"><div><CardTitle>Holdings and accounting</CardTitle><CardDescription>Cost basis, current value, and unrealized value are distinct. Valuation changes do not create income transactions.</CardDescription></div><div className="flex gap-2"><Button variant="outline" onClick={() => setShowAsset(true)}>Add asset</Button><Button variant="outline" onClick={() => setShowTrade(true)}>Record trade</Button><Button variant="outline" onClick={() => setShowFund(true)}>Fund account</Button><Button variant="outline" onClick={() => setShowPrice(true)}>Manual price</Button></div></div></CardHeader><CardContent className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase text-gray-500"><tr><th className="p-2">Asset</th><th className="p-2">Account</th><th className="p-2 text-right">Units</th><th className="p-2 text-right">Cost basis</th><th className="p-2 text-right">Current value</th><th className="p-2 text-right">Unrealized</th></tr></thead><tbody>{portfolio?.holdings.length ? portfolio.holdings.map((holding) => <tr key={`${holding.accountId}-${holding.asset.id}`} className="border-b last:border-0"><td className="p-2"><span className="font-semibold">{holding.asset.symbol}</span><span className="ml-2 text-xs text-gray-500">{holding.asset.name}</span></td><td className="p-2">{accounts.find((account) => account.id === holding.accountId)?.name || '—'}</td><td className="p-2 text-right">{holding.units.toLocaleString()}</td><td className="p-2 text-right">{money(holding.costBasis, currency)}</td><td className="p-2 text-right">{money(holding.marketValue, currency)}</td><td className={`p-2 text-right ${holding.unrealizedGain >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{money(holding.unrealizedGain, currency)}</td></tr>) : <tr><td className="p-5 text-center text-gray-500" colSpan={6}>No portfolio holdings yet.</td></tr>}</tbody></table></CardContent></Card>
    <Card><CardHeader><CardTitle>Recent investment events</CardTitle></CardHeader><CardContent className="space-y-2">{events.length ? events.slice(0, 10).map((event) => <div key={event.id} className="flex flex-wrap justify-between gap-2 rounded-lg border p-3 text-sm"><span><strong>{event.type}</strong> · {assets.find((asset) => asset.id === event.assetId)?.symbol || 'Account cash'}</span><span>{money(asNumber(event.baseAmount), currency)} · {new Date(event.tradeDate).toLocaleDateString()}</span></div>) : <p className="text-sm text-gray-500">Investment events are immutable. Record a funding transfer first, then purchases, sales, dividends, and adjustments.</p>}</CardContent></Card>
    {showAccount && <Panel title="New investment account" onClose={() => setShowAccount(false)}><form onSubmit={submitAccount} className="grid gap-3 sm:grid-cols-2"><Field label="Account name"><input required value={accountForm.name} onChange={(event) => setAccountForm({ ...accountForm, name: event.target.value })} className="input" /></Field><Field label="Institution"><input value={accountForm.institution} onChange={(event) => setAccountForm({ ...accountForm, institution: event.target.value })} className="input" /></Field><Field label="Account class"><select value={accountForm.type} onChange={(event) => setAccountForm({ ...accountForm, type: event.target.value as InvestmentAccountType })} className="input"><option>Exchange</option><option>Brokerage</option><option>Retirement</option><option>PreciousMetals</option><option>Manual</option><option>Other</option></select></Field><Field label="Liquidity"><select value={accountForm.liquidity} onChange={(event) => setAccountForm({ ...accountForm, liquidity: event.target.value as InvestmentAccount['liquidity'] })} className="input"><option>Liquid</option><option>Restricted</option><option>Illiquid</option></select></Field><label className="flex gap-2 text-sm"><input checked={accountForm.includeInNetWorth} type="checkbox" onChange={(event) => setAccountForm({ ...accountForm, includeInNetWorth: event.target.checked })} />Include in net worth</label><label className="flex gap-2 text-sm"><input checked={accountForm.includeInEmergencyReserve} type="checkbox" disabled={accountForm.liquidity !== 'Liquid'} onChange={(event) => setAccountForm({ ...accountForm, includeInEmergencyReserve: event.target.checked })} />Cash-like emergency reserve (liquid only)</label><div className="sm:col-span-2"><Button type="submit" disabled={saving}>Create account</Button></div></form></Panel>}
    {showAsset && <Panel title="New tracked asset" onClose={() => setShowAsset(false)}><form onSubmit={submitAsset} className="grid gap-3 sm:grid-cols-2"><Field label="Symbol"><input required value={assetForm.symbol} onChange={(event) => setAssetForm({ ...assetForm, symbol: event.target.value })} className="input" /></Field><Field label="Display name"><input required value={assetForm.name} onChange={(event) => setAssetForm({ ...assetForm, name: event.target.value })} className="input" /></Field><Field label="Asset class"><select value={assetForm.assetClass} onChange={(event) => setAssetForm({ ...assetForm, assetClass: event.target.value as InvestmentAsset['assetClass'] })} className="input"><option>Crypto</option><option>Stock</option><option>ETF</option><option>MutualFund</option><option>Bond</option><option>PreciousMetal</option><option>CashEquivalent</option><option>Retirement</option><option>Other</option></select></Field><Field label="Risk level"><select value={assetForm.riskLevel} onChange={(event) => setAssetForm({ ...assetForm, riskLevel: event.target.value as RiskLevel })} className="input"><option>Low</option><option>Medium</option><option>High</option><option>VeryHigh</option></select></Field>{assetForm.assetClass === 'Crypto' && <div className="sm:col-span-2 rounded-lg border p-3"><label className="text-sm font-medium">Find the canonical CoinGecko asset<div className="mt-1 flex gap-2"><input value={cryptoQuery} onChange={(event) => setCryptoQuery(event.target.value)} placeholder="Bitcoin, Ethereum…" className="input flex-1" /><Button type="button" variant="outline" disabled={searchingCrypto} onClick={() => void searchCrypto()}>{searchingCrypto ? 'Searching…' : 'Search'}</Button></div></label>{cryptoResults.length > 0 && <div className="mt-2 max-h-44 space-y-1 overflow-y-auto">{cryptoResults.map((result) => <button type="button" key={result.id} onClick={() => selectCrypto(result)} className="flex w-full items-center gap-2 rounded-md p-2 text-left text-sm hover:bg-gray-100 dark:hover:bg-gray-800">{result.image ? <img src={result.image} alt="" className="h-5 w-5 rounded-full" /> : <span className="h-5 w-5 rounded-full bg-gray-200" />}<span className="font-medium">{result.symbol}</span><span className="text-gray-500">{result.name}</span><span className="ml-auto text-xs text-gray-400">{result.marketCapRank ? `#${result.marketCapRank}` : ''}</span></button>)}</div>}<p className="mt-2 text-xs text-gray-500">Selection saves CoinGecko’s stable ID; prices are never inferred from the ticker.</p><input aria-label="CoinGecko ID" placeholder="bitcoin" value={assetForm.coinGeckoCoinId} onChange={(event) => setAssetForm({ ...assetForm, coinGeckoCoinId: event.target.value })} className="input mt-2" /></div>}<div className="sm:col-span-2"><Button type="submit" disabled={saving}>Add asset</Button></div></form></Panel>}
    {showTrade && <Panel title="Record a portfolio event" onClose={() => setShowTrade(false)}><form onSubmit={submitTrade} className="grid gap-3 sm:grid-cols-2"><Field label="Investment account"><select required value={tradeForm.investmentAccountId} onChange={(event) => setTradeForm({ ...tradeForm, investmentAccountId: event.target.value })} className="input"><option value="">Select account</option>{activeAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="Event type"><select value={tradeForm.type} onChange={(event) => setTradeForm({ ...tradeForm, type: event.target.value as InvestmentEvent['type'] })} className="input"><option>Buy</option><option>Sell</option><option>Dividend</option><option>Interest</option><option>Fee</option><option>Adjustment</option></select></Field>{['Buy', 'Sell'].includes(tradeForm.type) && <Field label="Asset"><select required value={tradeForm.assetId} onChange={(event) => setTradeForm({ ...tradeForm, assetId: event.target.value })} className="input"><option value="">Select asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.symbol} · {asset.name}</option>)}</select></Field>}<Field label="Units"><input type="number" min="0" step="any" value={tradeForm.units} onChange={(event) => setTradeForm({ ...tradeForm, units: event.target.value })} className="input" /></Field><Field label="Execution price"><input type="number" min="0" step="any" value={tradeForm.unitPrice} onChange={(event) => setTradeForm({ ...tradeForm, unitPrice: event.target.value })} className="input" /></Field><Field label={`Gross amount (${currency})`}><input required type="number" min="0" step="0.01" value={tradeForm.grossAmount} onChange={(event) => setTradeForm({ ...tradeForm, grossAmount: event.target.value })} className="input" /></Field><Field label="Fee"><input type="number" min="0" step="0.01" value={tradeForm.feeAmount} onChange={(event) => setTradeForm({ ...tradeForm, feeAmount: event.target.value })} className="input" /></Field><div className="sm:col-span-2"><Button type="submit" disabled={saving}>Record immutable event</Button></div></form></Panel>}
    {showFund && <Panel title="Fund an investment account" onClose={() => setShowFund(false)}><form onSubmit={submitFund} className="grid gap-3 sm:grid-cols-2"><Field label="Investment account"><select required value={fundForm.accountId} onChange={(event) => setFundForm({ ...fundForm, accountId: event.target.value })} className="input"><option value="">Select account</option>{activeAccounts.map((account) => <option key={account.id} value={account.id}>{account.name}</option>)}</select></Field><Field label="Cash wallet"><select required value={fundForm.sourceWalletId} onChange={(event) => setFundForm({ ...fundForm, sourceWalletId: event.target.value })} className="input"><option value="">Select wallet</option>{wallets.map((wallet) => <option key={wallet.id} value={wallet.id}>{wallet.name}</option>)}</select></Field><Field label={`Amount (${currency})`}><input required min="0.01" step="0.01" type="number" value={fundForm.amount} onChange={(event) => setFundForm({ ...fundForm, amount: event.target.value })} className="input" /></Field><div className="sm:col-span-2 rounded-lg bg-sky-50 p-3 text-sm text-sky-900">This creates a paired transfer and Funding event. It reduces wallet liquidity but is neither spending nor income.</div><div className="sm:col-span-2"><Button type="submit" disabled={saving}>Fund account</Button></div></form></Panel>}
    {showPrice && <Panel title="Record a manual price" onClose={() => setShowPrice(false)}><form onSubmit={submitPrice} className="grid gap-3 sm:grid-cols-2"><Field label="Asset"><select required value={priceForm.assetId} onChange={(event) => setPriceForm({ ...priceForm, assetId: event.target.value })} className="input"><option value="">Select asset</option>{assets.map((asset) => <option key={asset.id} value={asset.id}>{asset.symbol} · current {holdingsByAsset.get(asset.id)?.marketValue ? money(holdingsByAsset.get(asset.id)!.marketValue, currency) : 'unpriced'}</option>)}</select></Field><Field label={`Price (${currency})`}><input required min="0" step="any" type="number" value={priceForm.price} onChange={(event) => setPriceForm({ ...priceForm, price: event.target.value })} className="input" /></Field><div className="sm:col-span-2"><Button type="submit" disabled={saving}>Save manual valuation</Button></div></form></Panel>}
  </div>;
};

const Metric: React.FC<{ title: string; value: string; icon: React.ReactNode }> = ({ title, value, icon }) => <Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-sm text-gray-500">{icon}{title}</CardTitle></CardHeader><CardContent><p className="text-xl font-bold">{value}</p></CardContent></Card>;
const Empty: React.FC<{ text: string }> = ({ text }) => <div className="flex h-full items-center justify-center text-center text-sm text-gray-500">{text}</div>;
const Field: React.FC<{ label: string; children: React.ReactNode }> = ({ label, children }) => <label className="text-sm font-medium">{label}<div className="mt-1">{children}</div></label>;
const Panel: React.FC<{ title: string; onClose: () => void; children: React.ReactNode }> = ({ title, onClose, children }) => <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-4"><div role="dialog" aria-modal="true" aria-label={title} className="mx-auto mt-12 max-w-2xl rounded-2xl bg-white p-6 shadow-2xl dark:bg-gray-900"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-bold">{title}</h3><Button variant="ghost" onClick={onClose}>Close</Button></div>{children}</div></div>;
